Configurable formats + enum for views
BombenProdukt/livewire-calendar pull request #3
Opened 2023-05-07 13:57 UTC by haringsrob

2023-05-17 05:20 UTC, faustbrian commented
Hey, sorry for the late check-up. Didn't get a notification 😅

2023-05-17 05:21 UTC, faustbrian requested changes

2023-05-17 05:21 UTC, faustbrian commented on src/Enums/CalendarViews.php
> +enum CalendarViews: string
```suggestion
enum CalendarView: string
```

2023-05-17 05:23 UTC, faustbrian requested changes

2023-05-17 05:23 UTC, faustbrian commented on resources/views/calendar.blade.php
> +                                    {{$view->getViewLabel()}}
```suggestion
                                    {{ $view->getViewLabel() }}
```

2023-05-17 05:23 UTC, faustbrian commented on resources/views/calendar.blade.php
> +                                    wire:click="$set('selectedView', '{{$view->value}}')"
```suggestion
                                    wire:click="$set('selectedView', '{{ $view->value }}')"
```

2023-05-18 00:57 UTC, merged

2023-05-18 02:51 UTC, faustbrian commented
@haringsrob released in 2.3.0

2023-05-18 06:45 UTC, haringsrob commented
Thanks @faustbrian, sorry I did not fix the issues was busy with other stuff.